name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_PATH: ~/cdnc/mattermost-webapp

jobs:
#   test:
#     name: 'Run Test'
#     runs-on: ubuntu-latest
#     steps:
#     - name: Git checkout
#       uses: actions/checkout@v2
#     - name: Setup NodeJS
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - run: make test
  
  katalon-test:
    name: 'Katalon runs test'
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}/hw03-testing'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Run All Test Cases Collection" -apiKey= ${{ secrets.API_KEY }} -browserType="Chrome" --config -webui.autoUpdateDrivers=true'
  
  deploy:
    name: 'Update Server'
#     needs: [test]
    needs: [katalon-test]
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and deploy in server
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        PORT: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.PROJECT_PATH }}
          git pull origin master
          npm run build
